name: plfb-gfootball
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip<24
  - setuptools=65.*
  - wheel=0.38.*
  - cmake<4
  - make
  - ninja
  - pkg-config
  - cxx-compiler
  - libboost-devel=1.85.*
  - libboost-python-devel=1.85.*
  - sdl2
  - sdl2_image
  - sdl2_ttf
  - sdl2_gfx
  - mesalib
  - libglu
  - libgl-devel
  - libopengl-devel
  - libegl-devel
  - numpy=1.24.*
  - psutil=6.*
  - pip:
      - absl-py
      - cloudpickle
      - cmake<4
      - colorama
      - dataclasses-json
      - gym==0.21.0
      - gymnasium==0.29.0
      - h5py
      - "huggingface_hub[hf_transfer]>=0.20,<1.0"
      - hydra-core
      - kaggle-environments==1.14.1
      - matplotlib
      - omegaconf
      - "openai>=1.0,<3"
      - opencv-python
      - pandas
      - pydantic<2
      - "protobuf<6"
      - pygame>=1.9.6
      - pyyaml
      - requests
      - scikit-learn
      - structlog
      - tensorboardX
      - termcolor
      - torch==2.0.1
      - tqdm
      - "transformers>=4.46,<5"
