#!/usr/bin/env bash
# Shared environment defaults for PLfB public scripts. Source this file from repo scripts.

if [[ -n "${PLFB_COMMON_SH_LOADED:-}" ]] && declare -F plfb_cd_repo >/dev/null; then
  return 0 2>/dev/null || exit 0
fi
PLFB_COMMON_SH_LOADED=1

plfb_die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

plfb_script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${PLFB_REPO_ROOT:=$(cd "$plfb_script_dir/.." && pwd)}"
: "${PLFB_ROOT:=$PLFB_REPO_ROOT/football_llm}"
: "${PLFB_ARTIFACT_ROOT:=$PLFB_REPO_ROOT/plfb_artifacts}"
: "${PLFB_WORK_ROOT:=$PLFB_REPO_ROOT/runs}"
: "${PLFB_RUN_ROOT:=$PLFB_WORK_ROOT}"
: "${PLFB_HF_REPO:=ziyan98/plfb}"
: "${PLFB_PYTHON:=python3}"
: "${PLFB_GEN_MODEL:=gpt-4o-mini}"
: "${PLFB_OPENAI_CHAT_MODEL:=$PLFB_GEN_MODEL}"
: "${PLFB_OPENAI_AGG_MODEL:=gpt-4o}"
: "${PLFB_DATASET_PATH:=$PLFB_ARTIFACT_ROOT/football}"
: "${PLFB_OFFLINE_DATASET_PATH:=$PLFB_DATASET_PATH}"
: "${PLFB_IMAGINARY_DATASET_PATH:=$PLFB_DATASET_PATH/imaginary_dataset_0204}"
: "${PLFB_SAMPLED_DATA_PATH:=$PLFB_WORK_ROOT/sampled_data}"
: "${PLFB_MODEL_ROOT:=$PLFB_ARTIFACT_ROOT/artifacts/football}"
: "${PLFB_FILTER_PATH:=$PLFB_ARTIFACT_ROOT/book_derived/retrieval}"
: "${PLFB_PAPER_MERGED_DATA_CACHE_FILE:=$PLFB_IMAGINARY_DATASET_PATH/merged_data/v3datatrace_real_num=0&extra_real_traj_num=0&obs_stack_num=4&rollout_num=0.npz}"
: "${PLFB_STRICT_FIRST_STAGE_MODEL_PATH:=$PLFB_MODEL_ROOT/strict_repro_first_stage_ba0e02e/model_290000.d3}"
: "${PLFB_IRL_LOG_ROOT:=$PLFB_RUN_ROOT/IRL_LOG}"
: "${PLFB_MODEL_LOG_ROOT:=$PLFB_RUN_ROOT/IRL_LOG_MODEL}"
: "${PLFB_MERGED_DATA_CACHE_ROOT:=$PLFB_RUN_ROOT/merged_data_cache}"
: "${PLFB_MERGED_DATA_CACHE_FILE:=$PLFB_PAPER_MERGED_DATA_CACHE_FILE}"
: "${PLFB_EVAL_OUTPUT:=$PLFB_RUN_ROOT/eval_result}"
: "${PLFB_GFOOTBALL_LOGDIR:=$PLFB_RUN_ROOT/gfootball_logs}"
: "${SDL_VIDEODRIVER:=dummy}"

export PLFB_REPO_ROOT PLFB_ROOT PLFB_ARTIFACT_ROOT PLFB_WORK_ROOT PLFB_RUN_ROOT PLFB_HF_REPO PLFB_PYTHON
export PLFB_GEN_MODEL PLFB_OPENAI_CHAT_MODEL PLFB_OPENAI_AGG_MODEL
export PLFB_DATASET_PATH PLFB_OFFLINE_DATASET_PATH PLFB_IMAGINARY_DATASET_PATH
export PLFB_MODEL_ROOT PLFB_FILTER_PATH PLFB_PAPER_MERGED_DATA_CACHE_FILE PLFB_STRICT_FIRST_STAGE_MODEL_PATH
export PLFB_IRL_LOG_ROOT PLFB_MODEL_LOG_ROOT
export PLFB_SAMPLED_DATA_PATH PLFB_MERGED_DATA_CACHE_ROOT PLFB_MERGED_DATA_CACHE_FILE PLFB_EVAL_OUTPUT PLFB_GFOOTBALL_LOGDIR SDL_VIDEODRIVER
export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH="$PLFB_REPO_ROOT/football_llm:$PLFB_REPO_ROOT/football_llm/d3rlpy:$PLFB_REPO_ROOT/football_llm/setup/football:$PLFB_REPO_ROOT/plfb-uri:${PYTHONPATH:-}"

plfb_require_file() {
  [[ -f "$1" ]] || plfb_die "required file missing: $1"
}

plfb_require_dir() {
  [[ -d "$1" ]] || plfb_die "required directory missing: $1"
}

plfb_print_command() {
  printf ' +'
  printf ' %q' "$@"
  printf '\n'
}

plfb_run() {
  plfb_print_command "$@"
  "$@"
}

plfb_cd_repo() {
  cd "$PLFB_REPO_ROOT"
}

plfb_print_env() {
  cat <<ENVEOF
PLFB_REPO_ROOT=$PLFB_REPO_ROOT
PLFB_ROOT=$PLFB_ROOT
PLFB_ARTIFACT_ROOT=$PLFB_ARTIFACT_ROOT
PLFB_WORK_ROOT=$PLFB_WORK_ROOT
PLFB_PYTHON=$PLFB_PYTHON
PLFB_DATASET_PATH=$PLFB_DATASET_PATH
PLFB_OFFLINE_DATASET_PATH=$PLFB_OFFLINE_DATASET_PATH
PLFB_IMAGINARY_DATASET_PATH=$PLFB_IMAGINARY_DATASET_PATH
PLFB_PAPER_MERGED_DATA_CACHE_FILE=$PLFB_PAPER_MERGED_DATA_CACHE_FILE
PLFB_STRICT_FIRST_STAGE_MODEL_PATH=$PLFB_STRICT_FIRST_STAGE_MODEL_PATH
PLFB_SAMPLED_DATA_PATH=$PLFB_SAMPLED_DATA_PATH
PLFB_MODEL_ROOT=$PLFB_MODEL_ROOT
PLFB_FILTER_PATH=$PLFB_FILTER_PATH
PLFB_IRL_LOG_ROOT=$PLFB_IRL_LOG_ROOT
PLFB_MODEL_LOG_ROOT=$PLFB_MODEL_LOG_ROOT
PLFB_MERGED_DATA_CACHE_ROOT=$PLFB_MERGED_DATA_CACHE_ROOT
PLFB_MERGED_DATA_CACHE_FILE=$PLFB_MERGED_DATA_CACHE_FILE
ENVEOF
}
